Repository lindb/linsight, pull requests merged in 2023-05, with the labels that each got.

#4 [feat]: variable list can re-order
  web/src/features/dashboard/components/VariableList.tsx
  web/src/features/dashboard/components/variables.scss
  web/src/pages/EditDashboard.tsx
  web/src/stores/dashboard.store.ts
  web/yarn.lock
Labels: feature

#5 [refactor]: set dashboard uid to url when create dashboard successfull
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/Setting.tsx
  web/src/stores/dashboard.store.ts
Labels: refactor

#7 [ci]: add codecov
  .github/workflows/linsight.yml
  README.md
Labels: feature

#11 [feat]: add datasource category(visualization)
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/PanelSetting.tsx
  web/src/plugins/datasources/lindb/module.ts
  web/src/plugins/visualizations/gauge/module.ts
  web/src/plugins/visualizations/list/module.ts
  web/src/plugins/visualizations/pie/module.ts
  web/src/plugins/visualizations/table/module.ts
  web/src/plugins/visualizations/text/module.ts
  web/src/plugins/visualizations/timeseries/module.ts
  web/src/stores/datasource.store.ts
  web/src/types/datasource.ts
  web/src/types/theme.ts
  web/src/types/visualization.ts
Labels: feature

#13 [feat]: time picker/query time range
  go.mod
  go.sum
  plugin/datasource/lindb/client.go
  plugin/datasource/lindb/data_query.go
  plugin/datasource/lindb/data_query_test.go
  plugin/datasource/lindb/model.go
  web/src/App.tsx
  web/src/hooks/use.metric.ts
  web/src/images/logo-dark.svg
  web/src/images/logo.svg
  web/src/plugins/datasources/lindb/Datasource.ts
  web/src/styles/layout.scss
  web/src/types/datasource.ts
Labels: feature

#14 [feat]: zoom time range in time series chart/query variable editor
  README.md
  http/api/datasource.go
  web/custom.d.ts
  web/index.html
  web/src/App.tsx
  web/src/components/index.ts
  web/src/components/input/DatasourceSelect.tsx
  web/src/components/input/DatasourceSelectForm.tsx
  web/src/components/input/LinSelect.tsx
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/PanelEditor.tsx
  web/src/features/dashboard/components/VariableEditor.tsx
  web/src/features/dashboard/components/VariableList.tsx
  web/src/features/dashboard/components/ViewVariables.tsx
  web/src/features/dashboard/components/variables.scss
  web/src/features/dashboard/dashboard.scss
  web/src/features/explore/Explore.tsx
  web/src/hooks/index.ts
  web/src/hooks/use.variable.ts
  web/src/images/logo_title.svg
  web/src/plugins/datasources/lindb/Datasource.ts
  web/src/plugins/datasources/lindb/VariableEditor.tsx
  web/src/plugins/datasources/lindb/components/MetricNameSelect.tsx
  web/src/plugins/visualizations/timeseries/components/Legend.tsx
  web/src/plugins/visualizations/timeseries/components/TimeSeriesChart.tsx
  web/src/plugins/visualizations/timeseries/components/Tooltip.tsx
  web/src/plugins/visualizations/timeseries/components/chart.config.ts
  web/src/plugins/visualizations/timeseries/components/timeseries.scss
  web/src/stores/dashboard.store.ts
  web/src/stores/platform.store.ts
  web/src/types/dashboard.ts
  web/src/types/datasource.ts
  web/src/types/platform.ts
  web/src/utils/object.ts
Labels: feature

#16 [chore]: features desc in README
  README.md
Labels: feature

#21 [feat]: where condition editor
  plugin/datasource/lindb/model.go
  web/src/hooks/use.metric.ts
  web/src/plugins/datasources/lindb/components/WhereEditor.tsx
  web/src/plugins/datasources/lindb/query-edit.scss
Labels: feature

#22 [bug]: fix panel options modify ineffective
  web/src/components/dashboard/Panel.tsx
  web/src/features/dashboard/PanelEditor.tsx
  web/src/stores/panel.store.ts
Labels: feature

#26 [feat]: save variable selected value/init variable values when dashboard render
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/components/ViewVariables.tsx
  web/src/types/dashboard.ts
  web/src/utils/variable.ts
Labels: feature

#27 [feat]: row panel
  web/src/components/dashboard/AddPanelWidget.tsx
  web/src/components/dashboard/Panel.tsx
  web/src/constants/dashboard.ts
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/View.tsx
  web/src/features/dashboard/components/RowPanel.tsx
  web/src/features/dashboard/dashboard.scss
  web/src/stores/dashboard.store.ts
  web/src/styles/theme/_palette.scss
  web/src/utils/object.ts
Labels: feature

#28 [refactor]: sider nav style
  web/src/App.tsx
  web/src/styles/layout.scss
  web/src/styles/theme/_palette.scss
Labels: refactor

#29 [refactor]: panel/grid id
  web/src/components/dashboard/AddPanelWidget.tsx
  web/src/components/dashboard/Panel.tsx
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/PanelEditor.tsx
  web/src/features/dashboard/View.tsx
  web/src/features/dashboard/ViewPanel.tsx
  web/src/features/dashboard/components/ViewVariables.tsx
  web/src/stores/dashboard.store.ts
  web/src/types/visualization.ts
Labels: refactor

#30 [refactor]: panel editor
  web/src/components/dashboard/AddPanelWidget.tsx
  web/src/contexts/PanelEditContextProvider.tsx
  web/src/contexts/QueryEditContextProvider.tsx
  web/src/contexts/index.ts
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/PanelEditor.tsx
  web/src/features/dashboard/PanelSetting.tsx
  web/src/features/dashboard/dashboard.scss
  web/src/plugins/datasources/lindb/QueryEditor.tsx
  web/src/plugins/datasources/lindb/components/WhereEditor.tsx
  web/src/stores/dashboard.store.ts
  web/src/stores/index.ts
  web/src/stores/panel.store.ts
Labels: refactor

#32 [feat]: dashboard config use grafana data modal
  http/api/dashboard.go
  http/api/dashboard_test.go
  model/dashboard.go
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/dashboard/View.tsx
  web/src/features/dashboard/components/VariableEditor.tsx
  web/src/features/dashboard/components/VariableList.tsx
  web/src/features/dashboard/components/ViewVariables.tsx
  web/src/services/dashboard.service.ts
  web/src/stores/dashboard.store.ts
  web/src/types/dashboard.ts
  web/src/types/visualization.ts
Labels: feature

#33 [refactor]: format plugin
  web/src/components/dashboard/AddPanelWidget.tsx
  web/src/contexts/PanelEditContextProvider.tsx
  web/src/contexts/PlatformContextProvider.tsx
  web/src/features/dashboard/PanelSetting.tsx
  web/src/plugins/formats/data/data.ts
  web/src/plugins/formats/data/module.ts
  web/src/plugins/formats/time/module.ts
  web/src/plugins/formats/time/time.ts
  web/src/plugins/visualizations/gauge/module.ts
  web/src/plugins/visualizations/timeseries/TimeSeries.tsx
  web/src/plugins/visualizations/timeseries/components/TimeSeriesChart.tsx
  web/src/plugins/visualizations/timeseries/components/chart.config.ts
  web/src/plugins/visualizations/timeseries/types.ts
  web/src/stores/dashboard.store.ts
  web/src/types/format.ts
  web/src/types/visualization.ts
  web/src/utils/format.ts
Labels: refactor

#34 [feat]: CI support arm64
  .github/workflows/docker-latest.yml
  web/Makefile
Labels: feature

#37 [bug]: fix docker image not include web
  .github/workflows/docker-latest.yml
  Dockerfile-gh
Labels: bug

#38 [bug]: fix docker image not include web
  .github/workflows/docker-latest.yml
Labels: bug

#39 [feat]: add sync desc to docker hub
  .github/workflows/dockerhub-description.yml
Labels: feature

#41 [refactor]: time series chart options
  web/src/components/dashboard/Panel.tsx
  web/src/features/dashboard/PanelSetting.tsx
  web/src/features/dashboard/dashboard.scss
  web/src/plugins/visualizations/pie/components/PieChart.tsx
  web/src/plugins/visualizations/timeseries/OptionsEditor.tsx
  web/src/plugins/visualizations/timeseries/TimeSeries.tsx
  web/src/plugins/visualizations/timeseries/components/Legend.tsx
  web/src/plugins/visualizations/timeseries/components/TimeSeriesChart.tsx
  web/src/plugins/visualizations/timeseries/components/chart.config.ts
  web/src/plugins/visualizations/timeseries/images/line-dark.svg
  web/src/plugins/visualizations/timeseries/images/line.svg
  web/src/plugins/visualizations/timeseries/images/smooth-dark.svg
  web/src/plugins/visualizations/timeseries/images/smooth.svg
  web/src/plugins/visualizations/timeseries/module.ts
  web/src/plugins/visualizations/timeseries/types.ts
  web/src/styles/layout.scss
  web/src/types/visualization.ts
  web/src/utils/dataset.ts
  web/static/index.html
Labels: refactor

#42 [feat]: sync datasources after modify/time series chart support stepped
  http/api/boot.go
  web/index.html
  web/src/App.tsx
  web/src/Login.tsx
  web/src/components/common/Icon.tsx
  web/src/components/common/StatusTip.tsx
  web/src/components/dashboard/AddPanelWidget.tsx
  web/src/components/dashboard/Panel.tsx
  web/src/components/explore/AddToCharts.tsx
  web/src/features/chart/index.tsx
  web/src/features/dashboard/Dashboard.tsx
  web/src/features/explore/Explore.tsx
  web/src/features/setting/datasource/EditDataSource.tsx
  web/src/features/setting/datasource/ListDataSource.tsx
  web/src/features/setting/datasource/components/DeleteDatasourceButton.tsx
  web/src/pages/Dashboard.tsx
  web/src/pages/EditDashboard.tsx
  web/src/plugins/visualizations/timeseries/OptionsEditor.tsx
  web/src/plugins/visualizations/timeseries/components/Legend.tsx
  web/src/plugins/visualizations/timeseries/components/chart.config.ts
  web/src/plugins/visualizations/timeseries/components/timeseries.scss
  web/src/plugins/visualizations/timeseries/images/active-step.svg
  web/src/plugins/visualizations/timeseries/images/step-dark.svg
  web/src/plugins/visualizations/timeseries/images/step.svg
  web/src/plugins/visualizations/timeseries/types.ts
  web/src/stores/datasource.store.ts
  web/src/styles/layout.scss
Labels: feature
